export enum SuppliersActionTypes {
	SET_SUPPLIERS = 'SET_SUPPLIERS',
	SET_SUPPLIERS_GROUP = 'SET_SUPPLIERS_GROUP',
	SET_SUPPLIER_TITLE = 'SET_SUPPLIER_TITLE',
	ADD_SUPPLIER_COLUMNS = 'ADD_SUPPLIER_COLUMNS',
	DELETE_CATEGORY_COLUMN = 'DELETE_CATEGORY_COLUMN',
	ADD_SUPPLIER_LIST= 'ADD_SUPPLIER_LIST',
	UPDATE_SUPPLIER_NAME= 'UPDATE_SUPPLIER_NAME',
	DELETE_SUPPLIER_LIST= 'DELETE_SUPPLIER_LIST',
	UPDATE_ACTOR_PARAMS='UPDATE_ACTOR_PARAMS',
	CHANGE_SUPPLIER_UNIT_COST='CHANGE_SUPPLIER_UNIT_COST',
	CHANGE_SUPPLIER_PARAM='CHANGE_SUPPLIER_PARAM',
}
