export enum UsersActionTypes {
	ADD_LIST = 'ADD_LIST',
	SET_USER = 'SET_USER',
	SET_USERS = 'SET_USERS',
	REMOVE_LIST = 'REMOVE_LIST',
	ADD_DEFAULT_TASK = 'ADD_DEFAULT_TASK',
	DELETE_DEFAULT_TASK = 'DELETE_DEFAULT_TASK',
	UPDATE_DEFAULT_TASK = 'UPDATE_DEFAULT_TASK',
	CHANGE_DEFAULT_TASK_STATUS = 'CHANGE_DEFAULT_TASK_STATUS'
}

export enum UserActionTypes {
	SET_USER = 'SET_USER',
	SET_ALL_COMPANY_USERS = 'SET_ALL_COMPANY_USERS'
}




