export enum PermissionsActionTypes {
	UPDATE_USER_PERMISSION_TYPE = 'UPDATE_USER_PERMISSION_TYPE',
	UPDATE_USER_PERMISSION_STATUS = 'UPDATE_USER_PERMISSION_STATUS',
	UPDATE_USER_JOB_TITLE = 'UPDATE_USER_JOB_TITLE',
}
